version: '3.4'

services:
  rails-playground:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/rails-playground
      - gem_cache:/usr/local/bundle/gems
      - node_modules:/rails-playground/node_modules
    # env_file: .env
    environment:
      RAILS_ENV: development

volumes:
  gem_cache:
  node_modules: